### ISSUE TITLE
Editar figura 3.1 #16

### ISSUE THREAD

**Issue by jurricariet** [d4t4tur/DT5_actividad_empleo#16]
Se podrá poner la primera fila toda en negrita y más grande? así se nota que son categorías. Como en la 3.2

![image](https://user-images.githubusercontent.com/44036018/127687999-c358e68a-7dab-4108-b83c-d6eb32a8b70f.png)

**Comment by jurricariet** [comment]
Perdón, también sacar el "revisar" que quedó
![image](https://user-images.githubusercontent.com/44036018/127688840-eadb0fca-694e-4173-ada4-4713ca23fad3.png)

**Comment by hernancolazo** [comment]
Ya cambié la figura

**Comment by jurricariet** [comment]
![image](https://user-images.githubusercontent.com/44036018/128748709-a25f2164-6f38-4dcc-85c6-f95cc2ebac6f.png)

**Comment by TuQmano** [comment]
Esta es la que está en el repo https://github.com/d4t4tur/DT5_actividad_empleo/blob/master/imagenes/figura3.2.JPG

En el .Rmd está levantando la misma? Puede que le falte re build al bookdown aún @jurricariet

**Comment by jurricariet** [comment]
esa es la siguiente, yo digo esta: https://github.com/d4t4tur/DT5_actividad_empleo/blob/master/imagenes/figura3.1.JPG

**Comment by hernancolazo** [comment]
Listo!! Me parece que se volvió unas versiones atrás (puede ser) xq ya lo había hecho a este.

**Comment by jurricariet** [comment]
joya!
