### ISSUE TITLE
Cambios a la Figura 1.1

### ISSUE THREAD

**Issue by daianasparta** [d4t4tur/DT5_actividad_empleo#22]
@hernancolazo reedité la figura 1.1 en la sheet https://docs.google.com/spreadsheets/d/1Zhlznxw3YfGoD3e5YlcIDMdGeT58EoXsb1NFRVt4p1U/edit#gid=386462979. 
Entiendo que deberías formatearla nuevamente verdad?

**Comment by hernancolazo** [comment]
Ya editada.
