### ISSUE TITLE
Portada PDF: Cambiar "impacto" por "contribución"

### ISSUE THREAD

**Issue by TuQmano** [d4t4tur/DT5_actividad_empleo#3]

**Comment by TuQmano** [comment]
Hay que cambiar titulo de la pagina inicial del DT 5 @hernancolazo

**Comment by hernancolazo** [comment]
Ya cambié la portada "estuve un rato en entender que era la portada del "pdf y del jpg" emoticon de hombre con la palma abierta pegándose en la cara.

**Comment by TuQmano** [comment]
Cerrado en https://github.com/d4t4tur/DT5_actividad_empleo/commit/955c1c1e56d26be28fda8fb7bae71fbd8ae4626b
