### ISSUE TITLE
Cap. 1.2.1: agregar referencia al apartado anterior

### ISSUE THREAD

**Issue by TuQmano** [d4t4tur/DT5_actividad_empleo#9]

**Comment by jurricariet** [comment]
https://github.com/d4t4tur/DT5_actividad_empleo/blob/45dc6b73a3c56e97071145aa691d83cd5db99077/01-medicion-actividad.Rmd#L95

**Comment by TuQmano** [comment]
No lo probé aún, pero voy a arriesgar: es por caracteres espaciales (en este casó tilde en **desagregación**) que se complica. 

A proposito, y esto creo sería ideal para todo el DT, deberiamos acortar titulos / subtitulos @jurricariet  para mejor legibilidad. Cual
